/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedResidentsIndexRouteImport } from './routes/_authenticated/residents.index'
import { Route as AuthenticatedResidentsResidentIdRouteImport } from './routes/_authenticated/residents.$residentId'
import { Route as ApiPublicVeraExportRouteImport } from './routes/api/public/vera-export'

const AuthenticatedResidentsIndexRoute =
  AuthenticatedResidentsIndexRouteImport.update({
    id: '/_authenticated/residents/',
    path: '/residents/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedResidentsResidentIdRoute =
  AuthenticatedResidentsResidentIdRouteImport.update({
    id: '/_authenticated/residents/$residentId',
    path: '/residents/$residentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVeraExportRoute = ApiPublicVeraExportRouteImport.update({
  id: '/api/public/vera-export',
  path: '/api/public/vera-export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/residents/$residentId': typeof AuthenticatedResidentsResidentIdRoute
  '/api/public/vera-export': typeof ApiPublicVeraExportRoute
  '/residents/': typeof AuthenticatedResidentsIndexRoute
}
export interface FileRoutesByTo {
  '/residents/$residentId': typeof AuthenticatedResidentsResidentIdRoute
  '/api/public/vera-export': typeof ApiPublicVeraExportRoute
  '/residents': typeof AuthenticatedResidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/residents/$residentId': typeof AuthenticatedResidentsResidentIdRoute
  '/api/public/vera-export': typeof ApiPublicVeraExportRoute
  '/_authenticated/residents/': typeof AuthenticatedResidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/residents/$residentId' | '/api/public/vera-export' | '/residents/'
  fileRoutesByTo: FileRoutesByTo
  to: '/residents/$residentId' | '/api/public/vera-export' | '/residents'
  id:
    | '__root__'
    | '/_authenticated/residents/$residentId'
    | '/api/public/vera-export'
    | '/_authenticated/residents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedResidentsResidentIdRoute: typeof AuthenticatedResidentsResidentIdRoute
  ApiPublicVeraExportRoute: typeof ApiPublicVeraExportRoute
  AuthenticatedResidentsIndexRoute: typeof AuthenticatedResidentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/residents/': {
      id: '/_authenticated/residents/'
      path: '/residents'
      fullPath: '/residents/'
      preLoaderRoute: typeof AuthenticatedResidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/residents/$residentId': {
      id: '/_authenticated/residents/$residentId'
      path: '/residents/$residentId'
      fullPath: '/residents/$residentId'
      preLoaderRoute: typeof AuthenticatedResidentsResidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vera-export': {
      id: '/api/public/vera-export'
      path: '/api/public/vera-export'
      fullPath: '/api/public/vera-export'
      preLoaderRoute: typeof ApiPublicVeraExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedResidentsResidentIdRoute: AuthenticatedResidentsResidentIdRoute,
  ApiPublicVeraExportRoute: ApiPublicVeraExportRoute,
  AuthenticatedResidentsIndexRoute: AuthenticatedResidentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
