/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidentsResidentIdRouteImport } from './routes/residents.$residentId'
import { Route as ApiPublicVeraExportRouteImport } from './routes/api/public/vera-export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsResidentIdRoute = ResidentsResidentIdRouteImport.update({
  id: '/residents/$residentId',
  path: '/residents/$residentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVeraExportRoute = ApiPublicVeraExportRouteImport.update({
  id: '/api/public/vera-export',
  path: '/api/public/vera-export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/residents/$residentId': typeof ResidentsResidentIdRoute
  '/api/public/vera-export': typeof ApiPublicVeraExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/residents/$residentId': typeof ResidentsResidentIdRoute
  '/api/public/vera-export': typeof ApiPublicVeraExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/residents/$residentId': typeof ResidentsResidentIdRoute
  '/api/public/vera-export': typeof ApiPublicVeraExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/residents/$residentId' | '/api/public/vera-export'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/residents/$residentId' | '/api/public/vera-export'
  id: '__root__' | '/' | '/residents/$residentId' | '/api/public/vera-export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResidentsResidentIdRoute: typeof ResidentsResidentIdRoute
  ApiPublicVeraExportRoute: typeof ApiPublicVeraExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents/$residentId': {
      id: '/residents/$residentId'
      path: '/residents/$residentId'
      fullPath: '/residents/$residentId'
      preLoaderRoute: typeof ResidentsResidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vera-export': {
      id: '/api/public/vera-export'
      path: '/api/public/vera-export'
      fullPath: '/api/public/vera-export'
      preLoaderRoute: typeof ApiPublicVeraExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResidentsResidentIdRoute: ResidentsResidentIdRoute,
  ApiPublicVeraExportRoute: ApiPublicVeraExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
